### ISSUE TITLE
[BUG] webcal link from leagueathletics.com does not seem to work

### ISSUE THREAD

**Issue by geoffbeier** [JulienMalka/Linkal#6]
Linkal looks like just what I've been thinking about building for myself.

When I try to set it up with a calendar hosted on leagueathletics.com, I can't get it to work.

Here's my configuration

```
❯ cat calendars.json
```
```                         
{
  "calendars": {
    "webcal://www.LeagueAthletics.com/Feeds/ICal/?teams=1031498&org=arlingtonlittleleague.org": {
      "name": "Fall 2022 Majors Royals"
    }
  }
}
```

When I then start linkal by running

```
❯ cargo run -- --calendar-file calendars.json
    Finished dev [unoptimized + debuginfo] target(s) in 0.26s
     Running `target/debug/linkal --calendar-file calendars.json`
```

it appers to start with no errors. When I connect to it with the Mac OS calendar program, it tells me no calendars are available, and `cadaver` tells me

```
❯ cadaver http://localhost:8443/
dav:/> ls
Listing collection `/': collection is empty.
```

No further messages are printed to linkal's stdout/stderr.

I suspect I'm either missing something that should be obvious to me or just trying to use this for the wrong thing altogether.

**Comment by JulienMalka** [comment]
Hi, the problem you're facing here is that the calendar you've specified is not a caldav calendar, it is simply a website serving ical files. In the short term, what we should do about it is adding a check when parsing the json config file so that linkal complains loudly if the calendar specified do not correspond with a caldav endpoint. In the long term it would be interesting to also support these endpoints that just serve ical files, it would make Linkal more general.

**Comment by geoffbeier** [comment]
Thank you. I think I assumed it was a caldav calendar because the site in question (along with two similar other sites which use different software AFAICT) also offers a separate endpoint for just downloading an ICS file. I guess certain clients must behave better if they get the ical data from a "webcal" URL.

**Comment by JulienMalka** [comment]
I'll close this as I opened relevant feature requests.
